'use client';
import {useEffect,useState} from 'react'; import type {ComponentType} from 'react'; import {services as initialServices,cases as initialCases,posts as initialPosts} from '../../lib/data'; import {Save,Settings,FileText,Briefcase,Users,BarChart3,Lock,BookOpen,RotateCcw} from 'lucide-react';
type Lead={name:string;email:string;company:string;service:string;message:string;status:string};
const pretty=(x:any)=>JSON.stringify(x,null,2);
export default function Admin(){
 const [logged,setLogged]=useState(false),[pass,setPass]=useState(''),[tab,setTab]=useState('overview'),[saved,setSaved]=useState(false),[leads,setLeads]=useState<Lead[]>([]);
 const [headline,setHeadline]=useState('TURN MARKETING INTO MOMENTUM.'),[desc,setDesc]=useState('Solvexart brings strategy, paid media, search, creative and measurement together so your marketing works as one connected growth system.'),[primary,setPrimary]=useState('Build your growth plan'),[secondary,setSecondary]=useState('Explore our services');
 const [seo,setSeo]=useState({title:'Solvexart — Digital Marketing Agency',description:'Strategy, paid media, search, creative and measurement for measurable growth.',ga4:'',gtm:'',googleAds:'',meta:'',clarity:''});
 const [servicesJson,setServicesJson]=useState(pretty(initialServices)),[casesJson,setCasesJson]=useState(pretty(initialCases)),[postsJson,setPostsJson]=useState(pretty(initialPosts));
 useEffect(()=>{setLogged(sessionStorage.getItem('solvexart-admin')==='1');try{const c=JSON.parse(localStorage.getItem('solvexart-content')||'null');if(c){setHeadline(c.headline||headline);setDesc(c.desc||desc);setPrimary(c.primary||primary);setSecondary(c.secondary||secondary)}}catch{} try{const s=JSON.parse(localStorage.getItem('solvexart-settings')||'null');if(s)setSeo(s)}catch{} try{const l=JSON.parse(localStorage.getItem('solvexart-leads')||'[]');setLeads(l)}catch{} try{const s=localStorage.getItem('solvexart-services');if(s)setServicesJson(pretty(JSON.parse(s)))}catch{} try{const c=localStorage.getItem('solvexart-cases');if(c)setCasesJson(pretty(JSON.parse(c)))}catch{} try{const p=localStorage.getItem('solvexart-posts');if(p)setPostsJson(pretty(JSON.parse(p)))}catch{}},[]);
 const login=(e:any)=>{e.preventDefault();if(pass==='solvexart-admin'){sessionStorage.setItem('solvexart-admin','1');setLogged(true)}else alert('Demo password: solvexart-admin')};
 const save=()=>{try{const sv=JSON.parse(servicesJson),cs=JSON.parse(casesJson),ps=JSON.parse(postsJson);if(!Array.isArray(sv)||!Array.isArray(cs)||!Array.isArray(ps))throw new Error('Datasets must be arrays');localStorage.setItem('solvexart-services',JSON.stringify(sv));localStorage.setItem('solvexart-cases',JSON.stringify(cs));localStorage.setItem('solvexart-posts',JSON.stringify(ps));localStorage.setItem('solvexart-content',JSON.stringify({headline,desc,primary,secondary}));localStorage.setItem('solvexart-settings',JSON.stringify(seo));setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e:any){alert('Please check the JSON in the editor: '+e.message)}};
 const reset=()=>{if(confirm('Reset editable website content to the original Solvexart content?')){localStorage.removeItem('solvexart-content');localStorage.removeItem('solvexart-services');localStorage.removeItem('solvexart-cases');localStorage.removeItem('solvexart-posts');location.reload()}};
 if(!logged)return <div className="min-h-screen grid place-items-center bg-[#111] p-6"><form onSubmit={login} className="card p-8 w-full max-w-md"><Lock className="mb-5"/><p className="eyebrow">Solvexart Admin</p><h1 className="text-4xl font-black mt-3">Private dashboard</h1><p className="text-[#666] mt-3">Demo-ready content dashboard. Replace authentication with your production provider before launch.</p><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Admin password" className="w-full border-b border-black/20 py-4 mt-8 outline-none"/><button className="btn btn-dark w-full justify-center mt-6">Login</button></form></div>;
 const nav:Array<{id:string;label:string;Icon:ComponentType<{size?:number}>}>=[{id:'overview',label:'Overview',Icon:BarChart3},{id:'content',label:'Website Content',Icon:FileText},{id:'services',label:'Services',Icon:Briefcase},{id:'cases',label:'Case Studies',Icon:Briefcase},{id:'posts',label:'Resources',Icon:BookOpen},{id:'leads',label:'Leads',Icon:Users},{id:'settings',label:'SEO & Tracking',Icon:Settings}];
 return <div className="min-h-screen bg-[#f5f4ef]"><aside className="fixed inset-y-0 left-0 w-64 bg-[#111] text-white p-6 hidden md:block"><div className="font-black text-2xl tracking-[-.08em]">SOLVEXART<span className="text-lime">.</span></div><p className="eyebrow text-white/40 mt-10">Admin</p><div className="mt-5 grid gap-2">{nav.map(({id,label,Icon})=><button onClick={()=>setTab(id)} className={`text-left p-3 rounded-xl flex gap-3 items-center ${tab===id?'bg-white/10':''}`} key={id}><Icon size={17}/>{label}</button>)}</div><button onClick={reset} className="absolute bottom-16 text-white/50 text-sm flex items-center gap-2"><RotateCcw size={14}/>Reset content</button><button onClick={()=>{sessionStorage.removeItem('solvexart-admin');setLogged(false)}} className="absolute bottom-7 text-white/50 text-sm">Log out</button></aside><main className="md:ml-64 p-5 md:p-10 max-w-7xl"><div className="flex justify-between items-center gap-4"><div><p className="eyebrow">Solvexart Admin</p><h1 className="text-4xl font-black mt-2">{nav.find(n=>n.id===tab)?.label}</h1></div><button onClick={save} className="btn btn-dark"><Save size={17}/>{saved?'Saved':'Save changes'}</button></div>
 {tab==='overview'&&<div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4 mt-10">{[['Pages','07'],['Services',String(initialServices.length)],['Case Studies',String(initialCases.length)],['Resources',String(initialPosts.length)],['Leads',String(leads.length)]].map(([a,b])=><div className="card p-6" key={a}><p className="eyebrow">{a}</p><p className="text-4xl font-black mt-5">{b}</p></div>)}</div>}
 {tab==='content'&&<div className="grid lg:grid-cols-2 gap-5 mt-8"><div className="card p-7 space-y-5"><h2 className="text-2xl font-black">Homepage</h2><label className="eyebrow">Hero heading</label><input value={headline} onChange={e=>setHeadline(e.target.value)} className="w-full border-b border-black/20 py-4 text-2xl font-bold outline-none"/><label className="eyebrow block">Hero description</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={5} className="w-full border border-black/10 rounded-xl p-4 outline-none"/><label className="eyebrow block">Primary CTA</label><input value={primary} onChange={e=>setPrimary(e.target.value)} className="w-full border-b border-black/20 py-3 outline-none"/><label className="eyebrow block">Secondary CTA</label><input value={secondary} onChange={e=>setSecondary(e.target.value)} className="w-full border-b border-black/20 py-3 outline-none"/></div><div className="card p-7"><h2 className="text-2xl font-black">Content editing</h2><p className="text-[#666] mt-3 leading-relaxed">Services, case studies and resources can be edited in their dedicated tabs. The public pages read these saved datasets in the browser, while the original source content remains in the codebase as the fallback.</p><div className="mt-6 p-4 rounded-xl bg-[#111] text-white text-sm leading-relaxed">Tip: keep each service slug unchanged if you want existing Google-indexed URLs to keep working.</div></div></div>}
 {tab==='services'&&<div className="card p-5 mt-8"><p className="text-[#666] mb-4">Edit the complete service dataset. Keep JSON valid and keep each <b>slug</b> unique.</p><textarea value={servicesJson} onChange={e=>setServicesJson(e.target.value)} className="w-full min-h-[650px] font-mono text-sm border rounded-xl p-4 outline-none"/></div>}
 {tab==='cases'&&<div className="card p-5 mt-8"><p className="text-[#666] mb-4">Edit case-study titles, industries, challenge, strategy, results and SEO fields.</p><textarea value={casesJson} onChange={e=>setCasesJson(e.target.value)} className="w-full min-h-[500px] font-mono text-sm border rounded-xl p-4 outline-none"/></div>}
 {tab==='posts'&&<div className="card p-5 mt-8"><p className="text-[#666] mb-4">Edit resource titles, categories, excerpts, dates and article content.</p><textarea value={postsJson} onChange={e=>setPostsJson(e.target.value)} className="w-full min-h-[500px] font-mono text-sm border rounded-xl p-4 outline-none"/></div>}
 {tab==='leads'&&<div className="card overflow-hidden mt-8"><div className="p-6 border-b border-black/10 font-bold">Lead inbox</div>{leads.length===0?<p className="p-8 text-[#666]">No leads yet. Connect the contact form to an API/database to populate this inbox.</p>:leads.map((l,i)=><div className="p-5 border-b border-black/10 flex justify-between" key={i}><div><b>{l.name}</b><p className="text-sm text-[#666]">{l.email} · {l.company}</p></div><span>{l.status}</span></div>)}</div>}
 {tab==='settings'&&<div className="card p-7 mt-8 max-w-3xl space-y-6">{[['title','SEO Title'],['description','Meta Description'],['ga4','GA4 Measurement ID'],['gtm','Google Tag Manager ID'],['googleAds','Google Ads ID'],['meta','Meta Pixel ID'],['clarity','Microsoft Clarity ID']].map(([key,label])=><div key={key}><label className="eyebrow">{label}</label><input value={(seo as any)[key]} onChange={e=>setSeo({...seo,[key]:e.target.value})} className="w-full border-b border-black/20 py-3 outline-none"/></div>)}<p className="text-xs text-[#777]">Production note: connect these settings to your server/database and render tracking scripts conditionally after consent where required.</p></div>}
 </main></div>
}
