export type Service={slug:string;title:string;description:string;details:string;benefits:string[];process:string[];seoTitle:string;seoDescription:string};
export type CaseStudy={slug:string;title:string;industry:string;challenge:string;strategy:string;results:string[];seoTitle:string;seoDescription:string};
export const services:Service[]=[
{slug:'google-ads',title:'Google Ads',description:'High-intent paid search and Performance Max campaigns built around profitable growth.',details:'Solvexart builds Google Ads systems around clean measurement, focused targeting and continuous optimization.',benefits:['Search & Performance Max','Conversion tracking','Bid & budget optimization','Search-term management'],process:['Audit','Structure','Launch','Optimize'] ,seoTitle:'Google Ads Agency | Solvexart',seoDescription:'Performance-focused Google Ads management for ambitious businesses.'},
{slug:'seo',title:'SEO & Search',description:'Build durable organic visibility and attract customers actively searching for your offer.',details:'From technical foundations to content and authority, we turn search demand into a long-term acquisition channel.',benefits:['Technical SEO','Keyword strategy','Content systems','On-page optimization'],process:['Research','Plan','Publish','Improve'],seoTitle:'SEO Agency | Solvexart',seoDescription:'Strategic SEO services designed to grow qualified organic traffic.'},
{slug:'social-media',title:'Social Media',description:'Paid and organic social campaigns that turn attention into measurable business outcomes.',details:'Creative, targeting and measurement work together so social becomes a growth channel instead of a vanity metric.',benefits:['Meta advertising','Creative direction','Audience strategy','Performance reporting'],process:['Position','Create','Test','Scale'],seoTitle:'Social Media Marketing Agency | Solvexart',seoDescription:'Social media marketing and paid social campaigns from Solvexart.'},
{slug:'conversion-tracking',title:'Conversion Tracking',description:'Reliable measurement across ads, analytics, forms and customer journeys.',details:'We connect the signals that matter so you can trust your reporting and make better marketing decisions.',benefits:['GA4 & GTM','Google Ads conversions','Enhanced conversions','Offline conversion setup'],process:['Map','Implement','Validate','Monitor'],seoTitle:'Conversion Tracking Services | Solvexart',seoDescription:'Accurate conversion tracking and analytics implementation for marketing teams.'},
{slug:'analytics',title:'Analytics',description:'Clear dashboards and decision-ready reporting that explain what is working and why.',details:'Solvexart turns scattered marketing data into a clear view of performance, opportunity and next actions.',benefits:['GA4 analysis','Looker Studio','Attribution review','Performance reporting'],process:['Connect','Clean','Analyze','Act'],seoTitle:'Marketing Analytics Agency | Solvexart',seoDescription:'Marketing analytics, reporting and attribution support from Solvexart.'},
{slug:'web-development',title:'Web Development & CRO',description:'Fast, focused digital experiences designed to make every visit more valuable.',details:'We improve landing pages and digital experiences with a focus on clarity, speed and conversion.',benefits:['Landing pages','UX improvements','CRO testing','Performance'],process:['Discover','Design','Build','Test'],seoTitle:'Web Development & CRO | Solvexart',seoDescription:'Conversion-focused web development and CRO for growing businesses.'}
];
export const cases:CaseStudy[]=[{slug:'growth-system',title:'Building a clearer growth system',industry:'Home Services',challenge:'Marketing activity was fragmented and reporting did not clearly connect spend to outcomes.',strategy:'We tightened campaign structure, measurement and optimization around the customer journey.',results:['Cleaner conversion signals','Better budget visibility','A repeatable optimization process'],seoTitle:'Growth Marketing Case Study | Solvexart',seoDescription:'See how Solvexart approaches measurable growth systems.'},{slug:'ecommerce-performance',title:'Turning performance data into action',industry:'E-commerce',challenge:'The account had purchase activity but needed stronger visibility into the path from product view to checkout.',strategy:'We reviewed conversion signals, search terms, campaign structure and bidding inputs.',results:['Clearer funnel reporting','Stronger optimization priorities','More actionable weekly insights'],seoTitle:'E-commerce Marketing Case Study | Solvexart',seoDescription:'An Solvexart e-commerce performance marketing case study.'}];
export const posts=[{slug:'google-ads-budget',title:'How Much Should You Spend on Google Ads?',excerpt:'A practical framework for setting an initial paid search budget.',date:'2026-08-20',category:'Google Ads',content:'Your budget should follow your economics, search demand and testing needs. Start with a level that can generate enough conversion data, then adjust based on qualified results rather than clicks alone.'},{slug:'google-ads-vs-seo',title:'Google Ads vs SEO: Which Is Better?',excerpt:'Understand when paid search and organic search work best together.',date:'2026-08-18',category:'SEO',content:'Google Ads can create immediate visibility while SEO compounds over time. For many businesses, the strongest system uses both: paid campaigns capture high-intent demand while organic content expands the total search footprint.'}];
